### ISSUE TITLE
 Search Input Persists After Refresh

### ISSUE THREAD

**Issue by kvmanas** [wevm/vocs#120]
### **Description:**
The search input field does not reset its value when the browser tab is refreshed. This creates potential confusion for users as their previous search terms remain displayed even when they may be starting a new search.

### **Steps to Reproduce:**
1. Navigate to the page.
2. Enter a search term into the input field.
3. Refresh the browser tab.

**Comment by tmm** [comment]
This is [intentional](https://github.com/wevm/vocs/blob/main/src/app/components/SearchDialog.tsx#L29), but I agree, it makes sense to remove this behavior. Feel free to submit a PR.

**Comment by kvmanas** [comment]
submitted PR. please check @tmm
