### ISSUE TITLE
Build error: Could not resolve "@radix-ui/colors"

### ISSUE THREAD

**Issue by VanishMax** [wevm/vocs#154]
Hi! I am trying to set up Vocs with the steps from the documentation:

```bash
pnpm create vocs
cd vocs
pnpm i
pnpm dev
```

When I enter the `http://localhost:5173/`, the app fails with Vite error `ERROR: Could not resolve "@radix-ui/colors"`.

<img width="568" alt="image" src="https://github.com/wevm/vocs/assets/29180358/2020fbb1-0be1-4d88-bdba-aa64e001feda">

Supposedly, this is a packaging error, not coming from the users' side. I tried adding the `.npmrc` file (contents: `strict-peer-dependencies=false` and `auto-install-peers=true`) but it didn't help.

**Comment by limone-eth** [comment]
I'm having the same exact issue, using yarn@1.22.22, and tried running the quickstart command wit both NPM and Yarn

**Comment by jxom** [comment]
Unable to reproduce.

**Comment by maxov** [comment]
I had the same issue; try deleting the `.pnp.cjs` file given in the second part of the error. In my case, that file was present in my home directory (likely put there when I ran yarn install in my home directory by mistake), and that was messing up my build.
