### ISSUE TITLE
Question: Why is it named vocs?

### ISSUE THREAD

**Issue by yayxs** [wevm/vocs#180]
I've always had a request:
1. The rendered page must be SSR
2. I want the build tool to be vite
3. I can use MDX to write document content
4. I can use React to write the interface

Today I found you according to the number of stars marked by vite. I'm curious why the name is called vocs

**Comment by tmm** [comment]
V(ite)(d)ocs :)

**Comment by yayxs** [comment]
> V(ite)(d)ocs :)

I couldn't figure out why it was vocs at first, but then I suddenly remembered it on a cycling morning, haha. Same as I thought
