### ISSUE TITLE
Dynamically Update Variable in Code-Blocks

### ISSUE THREAD

**Issue by JamesLawton** [wevm/vocs#200]
I am looking to dynamically update a variable in a code-block when vocs is refreshed. I see there is options to do this in other markdown renderers, but wasn't able to get this updated in vocs. For example:

```
:::code-group

```bash [cURL]
curl -X POST -H "Content-Type: application/json" -H "X-Access-Key: {{ACCESS_KEY}}" 
:::

```

will simply output the string. Any ideas on this?

**Comment by jxom** [comment]
The following should work:

`example.mdx`
```mdx
:::code-group

export const ACCESS_KEY = 'abc'

```bash [cURL]
curl -X POST -H "Content-Type: application/json" -H "X-Access-Key: {ACCESS_KEY}" 
:::
```
