### ISSUE TITLE
Add copy button to code blocks

### ISSUE THREAD

**Issue by fakepixels** [wevm/vocs#214]
We're currently using Vocs for the documentation of multiple products including [Onchainkit.xyz ](https://onchainkit.xyz/) and [Smart Wallet](https://smartwallet.dev/). 

One of the most highly requested features is the ability to copy code blocks easily directly from the docs. Would be great if the team can add that feature for the next release.

**Comment by jxom** [comment]
Fixed on `alpha.60`.
