### ISSUE TITLE
Layouts are severely damaged on iOS 15 devices

### ISSUE THREAD

**Issue by ifshizuku** [wevm/vocs#43]
Today I was checking out Vocs on my phone and noticed the page had a serious layout error on my old phone, an iPhone 7 running iOS 15.8. It appears to have a desktop UI (I didn't open the "Request Desktop Site"), and you can see that it displays a search bar, and even buttons to toggle between dark and light color modes in a swipe-able area on the right side.

I've tested both Chrome 120 and Safari, the same, like:

![REAL](https://github.com/wevm/vocs/assets/73536163/7123c73f-485c-4b8e-8810-ab7ec21711c3)

To rule out some interference, I fired up an iPhone 7 simulator with iOS 15.5 in Xcode Simulator and the results were the same. The problem seems to be originating from iOS 15, I tried the iPhone SE2 again and it had the same problem with iOS 15 and not with iOS 17. Even the iPhone 13 with iOS 15.

![Simulator](https://github.com/wevm/vocs/assets/73536163/04e86db0-5e26-4bca-8961-898b1602577a)

I'm sorry I don't know the exact reason for it at the moment, but would it be a good idea to consider modifying some of the code for compatibility to ensure that iOS 15 devices can access it properly, after all the system isn't too old.

And most sites don't have similar problems, probably due to some overly advanced implementation?

I hope Vocs gets better and better, it's a great program.

**Comment by dalechyn** [comment]
![image](https://github.com/wevm/vocs/assets/35642018/3cac7f2c-5264-48fb-9834-ef4d7b83fc94)

Also just stumbled upon this, will check in my free time
