### ISSUE TITLE
Rendering issues when there is no `authors` field

### ISSUE THREAD

**Issue by PraneshASP** [wevm/vocs#44]
When only `date` field is added and no `authors` are passed, a `By` gets appended to the date.

![Screenshot 2024-01-20 at 15-52-10 Blog](https://github.com/wevm/vocs/assets/42379522/fcd36bf4-3c08-44b8-8325-bbae3d2dbc05)

<br>

I think the logic in this line (https://github.com/wevm/vocs/blob/main/src/app/components/Authors.tsx#L31-L35) has to be updated.

**Comment by tmm** [comment]
PR welcome! Should be quick fix.

**Comment by jxom** [comment]
Fixed on `1.0.0-alpha.30`
