### ISSUE TITLE
An unexpected NaN

### ISSUE THREAD

**Issue by Maidang1** [wevm/vocs#58]
when i just startup my project, an NaN show on the footer
![image](https://github.com/wevm/vocs/assets/50993231/0c635e89-e5eb-45a5-9587-a85d32743cb6)
![image](https://github.com/wevm/vocs/assets/50993231/25df55c2-66c0-41b0-8aaf-dea0d061305f)

```
vocs version: 1.0.0-alpha.30
```

**Comment by Maidang1** [comment]
I mybe found the problem, vocs use `git` to find the `lastUpdatedAt` of one page. But when i not init a git. this is an NaN. 
![image](https://github.com/wevm/vocs/assets/50993231/e991a46a-4a00-485b-828e-9c2b4c0bb21b)

**Comment by tmm** [comment]
Thanks!
