### ISSUE TITLE
`create-vocs` template doesn't gitignore dist

### ISSUE THREAD

**Issue by sor4chi** [wevm/vocs#66]
Hello, vocsers! Thanks for this great project.

When I created a foundation project for vocs using `create-vocs@1.0.0-alpha.3`, the output when built was generated in `/docs/dist` while `.gitignore` has `/dist`, so it was not ignored.

Is this the intended behavior?

https://github.com/wevm/vocs/blob/main/create-vocs/templates/default/_gitignore#L9

**Comment by tmm** [comment]
Nice spot! Feel free to submit a PR removing it if you want credit.
