### ISSUE TITLE
Document Admonitions usage and Steps

### ISSUE THREAD

**Issue by sambacha** [wevm/vocs#84]
When considering to use vocs, portability and conversion of existing documentation formatting is a key consideration. 

Knowing that I dont have to edit framework specific stuff is good to know

Docusarus style admonitions are used 

[https://github.com/wevm/vocs/blob/312a1786ab5a17c5b97cb6f52ab96ad57309602b/site/pages/docs/guides/markdown-snippets.mdx#L5](https://github.com/wevm/vocs/blob/312a1786ab5a17c5b97cb6f52ab96ad57309602b/site/pages/docs/guides/markdown-snippets.mdx#L5)

also this **Steps** keyword produces this

![](https://github.com/wevm/vocs/assets/32783916/42145971-a3e5-4047-bd32-23ce599e4a0c)

**Comment by jxom** [comment]
All of it is documented here: https://vocs.dev/docs/markdown, if that's what you mean.
