### ISSUE TITLE
Feature: LaTeX Support and Mermaid

### ISSUE THREAD

**Issue by sambacha** [wevm/vocs#85]
LaTeX and Mermaid support would be great

**Comment by jxom** [comment]
You can add support by adding the remark plugins here: http://localhost:5173/docs/api/config#markdownremarkplugins

- https://github.com/temando/remark-mermaid
- https://github.com/remarkjs/remark-math

**Comment by benediamond** [comment]
hi—a usage example of math / KaTeX would be very, very much appreciated here. though I've attempted to install the plugin, I am having trouble getting math to render. thanks in advance.
