### ISSUE TITLE
Support Tracking

### ISSUE THREAD

**Issue by codingwithmanny** [wevm/vocs#86]
# Context
In order to make documentation better, it would be great to track where people are doing and understand what actions they are taking.

# Solutions
Integrate the following via configuration for:
- Google Analytics
- UseFathom

# Proposal

Support the following convention for the tracking to allow for multiple forms of tracking to occur.

## Change 1/2

**File:** `vocs.config.ts`

```diff
import { defineConfig } from 'vocs'

export default defineConfig({
  title: 'Docs',
  sidebar: [
    {
      text: 'Getting Started',
      link: '/getting-started',
    },
    {
      text: 'Example',
      link: '/example',
    },
  ],
+ analytics: {
+   google: 'G-XXXXX ',
+   fathom: 'SITE-ID'
+ }
})
```

## Change 2/2

TBD - Need to config where in the templates this would exist, ideally just before closing `</body>` with conditionals for each,

**Comment by codingwithmanny** [comment]
Thanks for insight on this @tmm

**Comment by imaksp** [comment]
How to do this in v2, it seems head config option is removed.
